2.1
SELECT count(*) FROM PATIENT P WHERE P.P_ID IN 
(SELECT PATIENTID FROM B_DIAGNOSIS BD WHERE BD.DIESEASEID IN 
(SELECT DS_ID FROM DISEASE D WHERE D.DESCRIPTION = 'tumor' and D.TYPE = 'leukemia' and D.NAME = 'ALL'));

2.2
SELECT TYPE FROM DRUG D WHERE D.DR_ID IN 
(SELECT DRUGID FROM B_DRUGUSE BD WHERE BD.DRUGID NOT IN (-99) AND BD.PATIENTID IN 
(SELECT PATIENTID FROM B_DIAGNOSIS BD WHERE BD.DIESEASEID IN 
(SELECT DS_ID FROM DISEASE D WHERE D.DESCRIPTION = 'tumor')));

2.3
SELECT bcs.PATIENTID, mf.S_ID, mf.PB_ID, mf.MU_ID, mf.EXP FROM MICROARRAY_FACT mf INNER JOIN B_CLINICAL_SAMPLE bcs 
ON mf.S_ID = bcs.SAMPLEID
WHERE 
mf.PB_ID IN 
(SELECT p.PB_ID FROM PROBE p INNER JOIN GENE_FACT gf ON p.U_ID = gf.U_ID WHERE gf.CL_ID =  2)
AND mf.MU_ID = 1 
AND mf.S_ID IN 
(SELECT bcs.SAMPLEID
FROM B_DIAGNOSIS bd INNER JOIN B_CLINICAL_SAMPLE bcs 
ON bd.PATIENTID = bcs.PATIENTID 
WHERE bd.DIESEASEID = (SELECT DISTINCT DS_ID FROM DISEASE WHERE DISEASE.NAME LIKE ('ALL'))
);

2.4
SELECT STATS_T_TEST_INDEP(
CASE WHEN S_ID IN
(SELECT SAMPLEID FROM B_CLINICAL_SAMPLE BCS WHERE BCS.PATIENTID IN
(SELECT PATIENTID FROM B_DIAGNOSIS BD WHERE BD.DIESEASEID IN
(SELECT DS_ID FROM DISEASE D WHERE D.NAME = 'ALL'))) THEN 'A' ELSE 'B' END, EXP, 'STATISTIC', 'A') t_observed FROM MICROARRAY_FACT where S_ID IN 
(SELECT S_ID FROM MICROARRAY_FACT WHERE PB_ID IN 
(SELECT PB_ID FROM PROBE WHERE U_ID IN 
(SELECT U_ID FROM GENE_FACT WHERE GO_ID = '12502')));

SELECT STATS_T_TEST_INDEP(
CASE WHEN S_ID IN
(SELECT SAMPLEID FROM B_CLINICAL_SAMPLE BCS WHERE BCS.PATIENTID IN
(SELECT PATIENTID FROM B_DIAGNOSIS BD WHERE BD.DIESEASEID IN
(SELECT DS_ID FROM DISEASE D WHERE D.NAME = 'ALL'))) THEN 'A' ELSE 'B' END, EXP) two_sided_p_value FROM MICROARRAY_FACT where S_ID IN 
(SELECT S_ID FROM MICROARRAY_FACT WHERE PB_ID IN 
(SELECT PB_ID FROM PROBE WHERE U_ID IN 
(SELECT U_ID FROM GENE_FACT WHERE GO_ID = '12502')));

2.5
SELECT STATS_ONE_WAY_ANOVA(
CASE WHEN S_ID IN
(SELECT SAMPLEID FROM B_CLINICAL_SAMPLE BCS WHERE BCS.PATIENTID IN
(SELECT PATIENTID FROM B_DIAGNOSIS BD WHERE BD.DIESEASEID IN
(SELECT DS_ID FROM DISEASE D WHERE D.NAME = 'ALL'))) THEN 'A'

WHEN S_ID IN
(SELECT SAMPLEID FROM B_CLINICAL_SAMPLE BCS WHERE BCS.PATIENTID IN
(SELECT PATIENTID FROM B_DIAGNOSIS BD WHERE BD.DIESEASEID IN
(SELECT DS_ID FROM DISEASE D WHERE D.NAME = 'AML'))) THEN 'B'

WHEN S_ID IN
(SELECT SAMPLEID FROM B_CLINICAL_SAMPLE BCS WHERE BCS.PATIENTID IN
(SELECT PATIENTID FROM B_DIAGNOSIS BD WHERE BD.DIESEASEID IN
(SELECT DS_ID FROM DISEASE D WHERE D.NAME = 'Colon tumor'))) THEN 'C'

WHEN S_ID IN
(SELECT SAMPLEID FROM B_CLINICAL_SAMPLE BCS WHERE BCS.PATIENTID IN
(SELECT PATIENTID FROM B_DIAGNOSIS BD WHERE BD.DIESEASEID IN
(SELECT DS_ID FROM DISEASE D WHERE D.NAME = 'Breast tumor'))) THEN 'D' END, EXP, 'F_RATIO') f_ratio FROM MICROARRAY_FACT where S_ID IN 
(SELECT S_ID FROM MICROARRAY_FACT WHERE PB_ID IN 
(SELECT PB_ID FROM PROBE WHERE U_ID IN 
(SELECT U_ID FROM GENE_FACT WHERE GO_ID = '7154')));


SELECT STATS_ONE_WAY_ANOVA(
CASE WHEN S_ID IN
(SELECT SAMPLEID FROM B_CLINICAL_SAMPLE BCS WHERE BCS.PATIENTID IN
(SELECT PATIENTID FROM B_DIAGNOSIS BD WHERE BD.DIESEASEID IN
(SELECT DS_ID FROM DISEASE D WHERE D.NAME = 'ALL'))) THEN 'A'

WHEN S_ID IN
(SELECT SAMPLEID FROM B_CLINICAL_SAMPLE BCS WHERE BCS.PATIENTID IN
(SELECT PATIENTID FROM B_DIAGNOSIS BD WHERE BD.DIESEASEID IN
(SELECT DS_ID FROM DISEASE D WHERE D.NAME = 'AML'))) THEN 'B'

WHEN S_ID IN
(SELECT SAMPLEID FROM B_CLINICAL_SAMPLE BCS WHERE BCS.PATIENTID IN
(SELECT PATIENTID FROM B_DIAGNOSIS BD WHERE BD.DIESEASEID IN
(SELECT DS_ID FROM DISEASE D WHERE D.NAME = 'Colon tumor'))) THEN 'C'

WHEN S_ID IN
(SELECT SAMPLEID FROM B_CLINICAL_SAMPLE BCS WHERE BCS.PATIENTID IN
(SELECT PATIENTID FROM B_DIAGNOSIS BD WHERE BD.DIESEASEID IN
(SELECT DS_ID FROM DISEASE D WHERE D.NAME = 'Breast tumor'))) THEN 'D' END, EXP, 'SIG') p_value FROM MICROARRAY_FACT where S_ID IN 
(SELECT S_ID FROM MICROARRAY_FACT WHERE PB_ID IN 
(SELECT PB_ID FROM PROBE WHERE U_ID IN 
(SELECT U_ID FROM GENE_FACT WHERE GO_ID = '7154')));
